/**
 * Created by Administrator on 2016/10/17.
 */
var listData = {};
listData.listData00= {
    "success":"成功",
    "data":{
        "pageStart":0,
        "pageSize":8,
        "count":24,
        "list":[{
            "describe":"好吃不过呷哺呷哺",
            "title":"呷哺呷哺",
            "sysId":1,
            "coverImg":"anli/img1.jpg",
            "status":2
        },{
            "title":"人民日报",
            "sysId":2,
            "coverImg":"anli/img2.jpg",
            "status":2
        },{
            "describe":"北京体育大学是一所以教育,科技,文化于一身的大学.",
            "title":"北京体育大学",
            "sysId":3,
            "coverImg":"anli/img3.jpg",
            "status":2
        },{
            "title":"海淀驾校",
            "sysId":4,
            "coverImg":"anli/img4.jpg",
            "status":2
        },{
            "title":"平安基金",
            "sysId":5,
            "coverImg":"anli/img5.jpg",
            "status":2
        },{
            "describe":"华贸资本是一家实力及其雄厚的公司，旗下拥有...",
            "title":"华茂资本",
            "sysId":6,
            "coverImg":"anli/img6.jpg",
            "status":2
        },{
            "title":"千丝绣",
            "sysId":7,
            "coverImg":"anli/img7.jpg",
            "status":2
        },{
            "describe":"铭鹤书苑是一家多元化投资企业管理公司...",
            "title":"铭鹤书苑",
            "sysId":8,
            "coverImg":"anli/img8.jpg",
            "status":2
        }
        ]
    }
};
listData.listData01= {
    "success":"成功",
    "data":{
        "pageStart":1,
        "pageSize":8,
        "count":24,
        "list":[{
            "describe":"好吃不过呷哺呷哺",
            "title":"呷哺呷哺",
            "sysId":1,
            "coverImg":"anli/img1.jpg",
            "status":2
        },{
            "title":"人民日报",
            "sysId":2,
            "coverImg":"anli/img2.jpg",
            "status":2
        },{
            "describe":"北京体育大学是一所以教育,科技,文化于一身的大学.",
            "title":"北京体育大学",
            "sysId":3,
            "coverImg":"anli/img3.jpg",
            "status":2
        },{
            "title":"海淀驾校",
            "sysId":4,
            "coverImg":"anli/img4.jpg",
            "status":2
        },{
            "title":"平安基金",
            "sysId":5,
            "coverImg":"anli/img5.jpg",
            "status":2
        },{
            "describe":"华贸资本是一家实力及其雄厚的公司，旗下拥有...",
            "title":"华茂资本",
            "sysId":6,
            "coverImg":"anli/img6.jpg",
            "status":2
        },{
            "title":"千丝绣",
            "sysId":7,
            "coverImg":"anli/img7.jpg",
            "status":2
        },{
            "describe":"铭鹤书苑是一家多元化投资企业管理公司...",
            "title":"铭鹤书苑",
            "sysId":8,
            "coverImg":"anli/img8.jpg",
            "status":2
        }
        ]
    }
};
listData.listData02= {
    "success":"成功",
    "data":{
        "pageStart":2,
        "pageSize":8,
        "count":24,
        "list":[{
            "describe":"鲲鹏移民的出现带来了很多的便利,让那些...",
            "title":"鲲鹏移民",
            "sysId":1,
            "coverImg":"anli/img9.jpg",
            "status":2
        },{
            "title":"第67届艾美奖全程直击",
            "sysId":2,
            "coverImg":"anli/img10.jpg",
            "status":2
        },{
            "describe":"北京市海淀区汽车驾驶学校（简称海淀驾校或海...",
            "title":"海淀驾校",
            "sysId":3,
            "coverImg":"anli/img11.jpg",
            "status":2
        },{
            "describe":"北京大学体育馆是世界上首座专门为乒乓球比...",
            "title":"北京大学体育馆",
            "sysId":4,
            "coverImg":"anli/img12.jpg",
            "status":2
        },{
            "describe":"鲲鹏移民的出现带来了很多的便利,让那些...",
            "title":"鲲鹏移民",
            "sysId":5,
            "coverImg":"anli/img9.jpg",
            "status":2
        },{
            "title":"第67届艾美奖全程直击",
            "sysId":6,
            "coverImg":"anli/img10.jpg",
            "status":2
        },{
            "describe":"北京市海淀区汽车驾驶学校（简称海淀驾校或海...",
            "title":"海淀驾校",
            "sysId":7,
            "coverImg":"anli/img11.jpg",
            "status":2
        },{
            "describe":"北京大学体育馆是世界上首座专门为乒乓球比...",
            "title":"北京大学体育馆",
            "sysId":8,
            "coverImg":"anli/img12.jpg",
            "status":2
        }
        ]
    }
};